# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('cargo', models.PositiveSmallIntegerField(choices=[(13, 'Vereador'), (7, 'Deputado Estadual'), (8, 'Deputado Distrital'), (6, 'Deputado Federal'), (3, 'Senador'), (11, 'Prefeito'), (5, 'Governador'), (1, 'Presidente')])),
                ('agreg_regiao', models.PositiveSmallIntegerField(choices=[(0, 'Brasil'), (2, 'Estado'), (6, 'Municipio')])),
                ('regiao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NomePublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('num_acessos', models.BigIntegerField(verbose_name='Número de Acessos')),
            ],
            options={
                'verbose_name': 'Nome Público',
                'verbose_name_plural': 'Nomes Públicos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Pessoa')),
                ('num_acessos', models.BigIntegerField(verbose_name='Número de Acessos')),
            ],
            bases=('core.pessoa',),
        ),
        migrations.AddField(
            model_name='nomepublico',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
        ),
        migrations.AlterUniqueTogether(
            name='nomepublico',
            unique_together=set([('pessoa', 'nome')]),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidato'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together=set([('candidato', 'ano', 'cargo')]),
        ),
    ]
