# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coligacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('cargo', models.PositiveSmallIntegerField(choices=[(13, 'Vereador'), (7, 'Deputado Estadual'), (8, 'Deputado Distrital'), (6, 'Deputado Federal'), (3, 'Senador'), (11, 'Prefeito'), (5, 'Governador'), (1, 'Presidente')])),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('agreg_regiao', models.PositiveSmallIntegerField(choices=[(0, 'Brasil'), (2, 'Estado'), (6, 'Municipio')])),
                ('regiao', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Coligação',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(db_index=True, verbose_name='Número')),
                ('sigla', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidatura',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatura',
            name='resultado',
            field=models.CharField(default='NENHUM', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='num_acessos',
            field=models.BigIntegerField(default=0, verbose_name='Número de Acessos'),
        ),
        migrations.AlterField(
            model_name='nomepublico',
            name='num_acessos',
            field=models.BigIntegerField(default=0, verbose_name='Número de Acessos'),
        ),
        migrations.AlterUniqueTogether(
            name='coligacao',
            unique_together=set([('ano', 'cargo', 'codigo')]),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='coligacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coligacao'),
            preserve_default=False,
        ),
    ]
