# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171120_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Partido'),
            preserve_default=False,
        ),
    ]
