# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171120_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coligacao',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
