# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171120_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='resultado',
            field=models.CharField(max_length=50),
        ),
    ]
