# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171120_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('cargo', models.PositiveSmallIntegerField(choices=[(13, 'Vereador'), (7, 'Deputado Estadual'), (8, 'Deputado Distrital'), (6, 'Deputado Federal'), (3, 'Senador'), (11, 'Prefeito'), (5, 'Governador'), (1, 'Presidente')])),
                ('turno', models.CharField(max_length=1)),
                ('num_votos', models.BigIntegerField(verbose_name='Núm.Votos')),
                ('media', models.BigIntegerField(verbose_name='Média de Votos')),
                ('partido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partido')),
            ],
        ),
        migrations.AddField(
            model_name='candidatura',
            name='num_votos',
            field=models.BigIntegerField(null=True, verbose_name='Núm.Votos'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='coligacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Coligacao'),
        ),
    ]
