# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171202_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('agreg_regiao', models.PositiveSmallIntegerField(choices=[(0, 'Brasil'), (2, 'Estado'), (6, 'Municipio')])),
                ('descricao', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cargo',
            field=models.PositiveSmallIntegerField(choices=[(13, 'Vereador'), (7, 'Deputado Estadual'), (8, 'Deputado Distrital'), (6, 'Deputado Federal'), (5, 'Senador'), (11, 'Prefeito'), (3, 'Governador'), (1, 'Presidente')]),
        ),
        migrations.AlterField(
            model_name='coligacao',
            name='cargo',
            field=models.PositiveSmallIntegerField(choices=[(13, 'Vereador'), (7, 'Deputado Estadual'), (8, 'Deputado Distrital'), (6, 'Deputado Federal'), (5, 'Senador'), (11, 'Prefeito'), (3, 'Governador'), (1, 'Presidente')]),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='cargo',
            field=models.PositiveSmallIntegerField(choices=[(13, 'Vereador'), (7, 'Deputado Estadual'), (8, 'Deputado Distrital'), (6, 'Deputado Federal'), (5, 'Senador'), (11, 'Prefeito'), (3, 'Governador'), (1, 'Presidente')]),
        ),
    ]
