# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171208_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ue',
            options={'verbose_name': 'Localidade'},
        ),
        migrations.AlterField(
            model_name='votacao',
            name='media',
            field=models.BigIntegerField(null=True, verbose_name='Média de Votos'),
        ),
        migrations.AlterField(
            model_name='votacao',
            name='num_votos',
            field=models.BigIntegerField(default=0, verbose_name='Núm.Votos'),
        ),
        migrations.AlterUniqueTogether(
            name='ue',
            unique_together=set([('sigla', 'agreg_regiao')]),
        ),
    ]
