# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171208_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='primeira',
            field=models.NullBooleanField(default=None),
        ),
    ]
