# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_candidatura_primeira'),
        ('core', '0012_auto_20171209_0757'),
    ]

    operations = [
    ]
