# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20171209_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votacao',
            unique_together=set([('ano', 'cargo', 'turno', 'partido')]),
        ),
    ]
