# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_candidatura_total_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='setoreconomico',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together=set([('ano', 'cargo', 'candidato')]),
        ),
    ]
