# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171212_0805'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='candidatura',
            index_together=set([('ano', 'cargo', 'numero')]),
        ),
    ]
