# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171212_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatura',
            options={'ordering': ['ano']},
        ),
        migrations.AlterModelOptions(
            name='setoreconomico',
            options={'verbose_name': 'Setor Econômico', 'verbose_name_plural': 'Setores Econômicos'},
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='primeira',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together=set([]),
        ),
    ]
