# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171213_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='UE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UE'),
        ),
    ]
